import i18n, { Resource } from "i18next";
import { initReactI18next } from "react-i18next";

const resources: Resource = {
	en: {
		translation: {
			findDentist: "Find your Dental Doctor",
			inquire: "Inquire Now",
			searchDentalClinic: "Search for Dental Clinic...",
			needHelp: "Need help?",
			lookingFor:
				"Looking for an immediate Dental advice or planning to have a dental appointment?",
			availableInTown: "We have an available doctor in town!",
			canvasNow: "Canvas Now!",
			map: "Map",
			seamlessTransaction: "For a seamless experience",
			accessNow: "Access us now!",
			shareLink: "Share Link!",
			availableClinics:
				"We have Doctors in these hospitals who are ready to serve you!",
			"Dental Clinics Available": "Dental Clinics Available",
			listYourClinic: "List Your Dental Clinic",
			viewMoreClinic: "View more Dental Clinic",
			viewProfile: "View Profile",
			commonConditions: "Common Conditions",
			commonConditionsDescription:
				"Easily access doctors treating these conditions",
			viewAll: "View All",
			commonServices: "Common Services",
			commonServicesDescription:
				"Easily access doctors offering these services",
			search: "Search...",
			searchClinic: "Search Clinic",
			conditions: "Conditions",
			services: "Services",
			general: "General",
			aboutUs: "About us",
			termsAndConditions: "Terms and Conditions",
			privacyPolicy: "Privacy Policy",
			socialMedia: "Social Media",
			forPatients: "For Patients",
			forDoctors: "For Doctors",
			listYourDentalClinic: "List your dental clinic",
			createAccount: "Create an account",
			logIn: "Log in",
			dashboardDescription:
				"Welcome to your dashboard, manage clinics, doctors, and your profile here",
			totalDoctors: "Total Doctors",
			clinics: "Clinics",
			registeredDoctors: "Registered doctors in the platform",
			registeredClinics: "Registered clinics in the platform",
			verifiedDoctors: "Verified Doctors",
			verifiedDoctorsInPlatform: "Doctors verified in the platform",
			months: "months",
			month: "month",
			days: "days",
			day: "day",
			showTotalChart: "Showing total visitors for the last",
			doctors: "Doctors",
			manageDoctors: "Manage Doctors",
			visits: "Visits",
			name: "Name",
			licenseNumber: "License Number",
			status: "Status",
			actions: "Actions",
			viewDoctorDetails: "View Doctor Details",
			verifyDoctor: "Verify Doctor",
			manageClinics: "Manage Clinics",
			clinicName: "Clinic Name",
			doctor: "Doctor",
			viewClinic: "View Clinic",
			activate: "Activate",
			deactivate: "Deactivate",
			clinic: "clinic",
			promptDeactivateClinic: "Are you sure you want to deactivate",
			type: "Type",
			toConfirm: "to confirm",
			cancel: "Cancel",
			confirm: "Confirm",
			subscriptions: "Subscriptions",
			manageSubscription: "Manage Subscription",
			addNewSubscription: "Add New Subscription",
			showHideColumn: "Show/Hide Column",
			subscription: "Subscription",
			subscriptionName: "Subscription Name",
			duration: "Duration",
			price: "Price",
			description: "Description",
			noResults: "No results",
			year: "year",
			years: "years",
			and: "and",
			edit: "Edit",
			delete: "Delete",
			subscriptionToast: "Subscription",
			created: "created",
			deleted: "deleted",
			updated: "updated",
			successfully: "successfully",
			accessibilityCreationError: "Accessibility creation error",
			addSubscription: "Add Subscription",
			deleteSubscription: "Delete Subscription",
			editSubscription: "Edit Subscription",
			close: "Close",
			createNew: "Create",
			transactions: "Transactions",
			listOfTransactions: "List of Transactions",
			amount: "Amount",
			paidAt: "Paid on",
		},
	},
	fil: {
		translation: {
			findDentist: "Hanapin ang Iyong Dentista",
			inquire: "Mag-inquire Ngayon",
			searchDentalClinic: "Maghanap ng Dental Clinic...",
			needHelp: "Kailangan ng tulong?",
			lookingFor:
				"Naghahanap ng agarang payo sa ngipin o nagpaplanong magkaroon ng appointment sa dentista?",
			availableInTown: "Mayroon kaming available na doktor sa bayan!",
			canvasNow: "Mag-canvass Ngayon!",
			map: "Mapa",
			seamlessTransaction: "Para sa isang walang putol na karanasan",
			accessNow: "access na ngayon!",
			shareLink: "Ibahagi ang Link!",
			availableClinics:
				"Mayroon kaming mga doktor sa mga ospital na ito na handang maglingkod sa iyo!",
			"Dental Clinics Available": "Mga Available na Dental Clinic",
			listYourClinic: "Ilista ang Iyong Dental Clinic",
			viewMoreClinic: "Tingnan ang iba pang Dental Clinic",
			viewProfile: "Tingnan ang profile",
			commonConditions: "Mga Karaniwang Kondisyon",
			commonConditionsDescription:
				"Madaling ma-access ang mga doktor na tumutukoy sa mga kondisyong ito.",
			viewAll: "Tingnan Lahat",
			commonServices: "Mga Karaniwang Serbisyo",
			commonServicesDescription:
				"Madaling ma-access ang mga doktor na nag-aalok ng mga serbisyong ito.",
			search: "Maghanap...",
			searchClinic: "Maghanap ng Klinik",
			conditions: "Mga Kondisyon",
			services: "Mga Serbisyo",
			general: "Pangkalahatang",
			aboutUs: "Tungkol sa amin",
			termsAndConditions: "Mga Tuntunin at Kondisyon",
			privacyPolicy: "Privacy Policy",
			socialMedia: "Social Media",
			forPatients: "Para sa mga pasyente",
			forDoctors: "Para sa mga doktor",
			listYourDentalClinic: "Ilista ang iyong dental clinic",
			createAccount: "Gumawa ng account",
			logIn: "Mag-log in",
			dashboardDescription:
				"Maligayang pagdating sa iyong dashboard, pamahalaan ang mga klinika, doktor, at ang iyong profile dito",
			clinics: "Mga klinika",
			totalDoctors: "Kabuuang mga doktor",
			registeredDoctors: "Mga rehistradong doktor sa platform",
			registeredClinics: "Mga rehistradong klinika sa platform",
			verifiedDoctors: "Mga doktor na naverify sa platform",
			verifiedDoctorsInPlatform: "Doktor na verify sa platform",
			showTotalChart: "Pagpapakita ng kabuuang mga bisita para sa huling",
			months: "na buwan",
			month: "buwan",
			days: "na araw",
			day: "araw",
			visits: "Mga pagbisita",
			doctors: "Mga doktor",
			manageDoctors: "Pamahalaan ang mga doktor",
			name: "Pangalan",
			licenseNumber: "Numero ng Lisensya",
			status: "Katayuan",
			actions: "Mga Aksyon",
			viewDoctorDetails: "Tingnan ang Mga Detalye ng Doktor",
			verifyDoctor: "Tiyakin ang Doktor",
			clinicName: "Pangalan ng Klinika",
			manageClinics: "Pamahalaan ang mga Klinika",
			doctor: "Doktor",
			viewClinic: "Tingnan ang Klinika",
			activate: "I-activate",
			deactivate: "I-deactivate",
			clinic: "klinika",
			promptDeactivateClinic: "Sigurado ka bang gusto mong i-deactivate",
			type: "I-type ang",
			toConfirm: "upang kumpirmahin",
			cancel: "Kanselahin",
			confirm: "Kumpirmahin",
			subscriptions: "Subscriptions",
			close: "Isara",
			createNew: "Lumikha ng bago",
			editSubscription: "I-edit ang Subscription",
			deleteSubscription: "Tanggalin ang Subscription",
			addSubscription: "Magdagdag ng Subscription",
			accessibilityCreationError: "Mayroong error sa paggawa ng accessibility",
			successfully: "ng matagumpay",
			subscriptionToast: "Ang iyong subscription ay",
			updated: "na-update na",
			deleted: "na-tanggal na",
			created: "na-gawa na",
			manageSubscription: "Pamahalaan ang Subscription",
			addNewSubscription: "Magdagdag ng Bagong Subscription",
			showHideColumn: "Ipakita / Itago ang Haligi",
			subscription: "Subscription",
			subscriptionName: "Pangalan ng Subscription",
			duration: "Tagal ng panahon",
			price: "Presyo",
			description: "Paglalarawan",
			noResults: "No results.",
			years: "na taon",
			year: "taon",
			and: "at",
			edit: "I-edit",
			delete: "Tanggalin",
			transactions: "Mga transaksyon",
			listOfTransactions: "Listahan ng mga Transaksyon",
			amount: "Halaga",
			paidAt: "Binayaran noong",
		},
	},
};

i18n
	.use(initReactI18next) // passes i18n down to react-i18next
	.init({
		resources,
		lng: "en",
		fallbackLng: "en",
		// language to use, more information here: https://www.i18next.com/overview/configuration-options#languages-namespaces-resources
		// you can use the i18n.changeLanguage function to change the language manually: https://www.i18next.com/overview/api#changelanguage
		// if you're using a language detector, do not define the lng option

		interpolation: {
			escapeValue: false, // react already safes from xss
		},
	});

export default i18n;
